name: sample_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animations: ^2.0.11
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  flutter_tesseract_ocr: ^0.4.23
  gap: ^3.0.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  restart_app: ^1.2.1
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  

  flutter_web_plugins: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
